"""Adaptive bounded NCP configuration screen; one training process at a time."""
import copy
import itertools
import json
from pathlib import Path
import subprocess
import sys

import autoresearch as r
import experiment_reports as reports
import ncp_campaign as c

AXES={
    'prediction_weight':[.1,.03,.3], 'feedback_scale':[.1,.3], 'layers':[1],
    'after_layer':[1,2], 'chunk_size':[2,8], 'entries':[16,32,128],
    'lr':[.0003,.003], 'vq_weight':[.1], 'ce_weight':[.1,1.],
}


def records():
    return [c.read(p) for p in sorted(c.HERE.glob('trial-*/result.json'))]


def options():
    base=c.candidate('N-RMS'); choices={}
    for key,values in AXES.items():
        for value in values:
            name='R-'+key+str(value); candidate=copy.deepcopy(base)
            candidate['ncp'][key]=value
            choices[name]=dict(candidate=r.validate_candidate(candidate),axis=key,control='N-RMS',
                hypothesis=f'Change only {key} to {value} on normalized NCP to test quality versus its stable unit-weight control')
    return choices


def choose(history,choices):
    done={x['label'] for x in history if x['seed']==42}
    pending=[x for x in choices if x not in done]
    if not pending: return None
    if 'R-prediction_weight0.1' in pending: return 'R-prediction_weight0.1'
    candidates=[x for x in history if x['seed']==42 and x['label'] in choices]
    if candidates:
        last=candidates[-1]
        base=next(x for x in history if x['label']=='N-RMS' and x['seed']==42)
        healthy=last['status']=='completed' and not (last.get('ncp_health') or {}).get('collapsed',False)
        improved=healthy and last['metrics']['val_bpb']<base['metrics']['val_bpb']
        if improved:
            same=[x for x in pending if choices[x]['axis']==choices[last['label']]['axis']]
            if same: return same[0]
    # Otherwise cover an under-tested causal axis before repeating its settings.
    counts={key:sum(x['label'] in choices and choices[x['label']]['axis']==key for x in candidates) for key in AXES}
    return min(pending,key=lambda x:(counts[choices[x]['axis']],list(AXES).index(choices[x]['axis'])))


def publish():
    def git(*args):
        return subprocess.check_output(['git',*args],cwd=r.ROOT,text=True,stderr=subprocess.STDOUT,timeout=60).strip()
    expected='https://github.com/VesperEngineering/vesper-sparse-concept-lab.git'
    assert git('remote','get-url','--push','origin')==expected
    assert git('branch','--show-current')=='research/overnight-20260915'
    staged=git('diff','--cached','--name-only').splitlines()
    assert all(x.startswith('reports/') for x in staged),'Unrelated staged changes; publication deferred'
    paths=['reports/README.md','reports/index.json']
    paths += [str(p.relative_to(r.ROOT)) for p in (r.ROOT/'reports/experiments').glob('ncp-20260915*')]
    # Source archives are byte-preserved by .gitattributes and generated by the reporter.
    paths += ['reports/source-snapshots']
    git('add','--',*paths)
    if git('diff','--cached','--name-only'):
        count=len(records())
        git('-c','user.name=VesperEngineering','-c','user.email=admin@novaaetus.com',
            'commit','-m',f'Report NCP campaign through trial {count}')
    def execute(command,**kwargs):
        return subprocess.run(['git','-c','http.sslBackend=openssl',*command[1:]],timeout=60,**kwargs)
    result=reports.publish(execute=execute)
    c.log('PUBLISHED '+result['publication_commit']+' remote verified')
    r.write_json(c.HERE/'publication-result.json',dict(kind='publication',status='completed',**result))


def screen(publish_results=False):
    choices=options()
    r.write_json(c.HERE/'normalized-search-space.json',choices)
    for label,option in choices.items():
        r.write_json(c.HERE/'candidates'/f'{label}.json',option['candidate'])
    while c.remaining()>7200:
        history=records(); label=choose(history,choices)
        if label is None:
            c.log('Normalized one-factor screen complete; inspect evidence before next bounded extension')
            return
        option=choices[label]
        r.write_json(c.HERE/'next-selection.json',dict(label=label,hypothesis=option['hypothesis'],
            evidence=[dict(label=x['label'],status=x['status'],metrics=x['metrics']) for x in history if x['seed']==42]))
        result=c.trial(label,42,option['hypothesis'],'screen',option['control'])
        if result is None: return
        if result['status']!='completed':
            last=sorted(c.HERE.glob('trial-*/result.json'))[-1]
            text=(last.parent/'run.log').read_text(errors='replace')
            if 'Invalid training loss' not in text and 'out of memory' not in text.lower():
                raise RuntimeError('Unclassified failure requires diagnosis: '+str(last))
            c.log('Invalid candidate preserved; skip and continue bounded screen')
        if publish_results:
            try: publish()
            except Exception as exc: c.log('Publication deferred; local results retained: '+repr(exc))
    c.log('Confirmation/report reserve reached; no further screening launch')


if __name__=='__main__':
    if '--self-test' in sys.argv:
        choices=options()
        base=dict(label='N-RMS',seed=42,status='completed',metrics={'val_bpb':.636})
        assert choose([base],choices)=='R-prediction_weight0.1'
        good=dict(label='R-prediction_weight0.1',seed=42,status='completed',metrics={'val_bpb':.632},ncp_health={'collapsed':False})
        assert choose([base,good],choices)=='R-prediction_weight0.03'
        failed=dict(good,status='failed',metrics=None)
        assert choose([base,failed],choices)=='R-feedback_scale0.1'
        # Confirmation results never choose a selection-seed configuration.
        assert choose([base,dict(good,seed=43)],choices)=='R-prediction_weight0.1'
        assert len({json.dumps(x['candidate'],sort_keys=True) for x in choices.values()})==len(choices)
        print('PASS: bounded selection, failure skipping, independent-seed isolation, unique configurations')
    elif '--publish-only' in sys.argv: publish()
    else: screen('--publish' in sys.argv)
